version: '3'
services:
  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: test:6:1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181

  zoo1:
    image: zookeeper:latest
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    environment:
      ZOO_MY_ID: 1
      SERVERS: zoo1

  webapp:
    build: .
    ports:
      - "80:80"